# Icônes du lot « outils et technique » : livre, parchemin, rapport, courrier, boîtes aux
# lettres, outils (marteau, clé, ciseaux, engrenage, boîte à outils), énergie et électronique
# (batterie, tableau de commande, capteur), arrosage automatique, microscope, éprouvette, robot.
# Format commun : voir scripts/icones/build.py.
#
# Les icônes sont décrites en « calques » : chaque calque est une grille 16×16 où une majuscule
# désigne une matière (ombrée automatiquement : reflet en haut à gauche, ombre en bas à droite,
# contour 1 px très sombre de la teinte de la matière posé autour) et une minuscule / un chiffre
# une couleur fixe (détails). Les calques sont empilés : le contour d'un calque passe par-dessus
# les calques du dessous, ce qui sépare proprement les objets qui se croisent.
import math

from PIL import Image

# matière : (contour, ombre, moyen, reflet)
MATS = {
    'A': ('#1e2833', '#64707e', '#9aa8b8', '#dfe7ef'),  # acier
    'W': ('#3a2414', '#6a4426', '#8a5a34', '#b07a48'),  # bois
    'R': ('#4a1418', '#8a2a30', '#c8434a', '#f07a6a'),  # rouge
    'P': ('#4a3424', '#d8c6a8', '#f4ead8', '#ffffff'),  # papier
    'Q': ('#4a3018', '#c89a58', '#e8c888', '#f8e4b4'),  # parchemin
    'B': ('#163a5c', '#2a70b0', '#4aa0e0', '#9ad0f4'),  # bleu (boîte aux lettres, eau)
    'Y': ('#3a2414', '#c7862a', '#f2c040', '#fbe38a'),  # or, laiton
    'T': ('#24384a', '#a8c4d8', '#d8eaf4', '#ffffff'),  # verre
    'S': ('#141c2a', '#34405a', '#4e5c78', '#7686a4'),  # ardoise (boîtiers, microscope)
}
# couleur fixe : (couleur, contour posé autour quand elle touche le vide, ou None)
FIX = {
    'n': ('#b8a07a', None),   # lignes d'écriture
    'q': ('#a87838', None),   # parchemin enroulé (spirale)
    'k': ('#4a3424', None),   # trait sombre sur papier
    'x': ('#141c2a', '#141c2a'),  # noir bleuté (fentes, visière)
    'w': ('#ffffff', None),
    'r': ('#e04848', '#4a1418'), 'h': ('#8a2a30', '#4a1418'), 'j': ('#f8a090', '#4a1418'),
    'g': ('#2f6e2c', '#1f4a22'), 'l': ('#4a9a3a', '#1f4a22'), 'm': ('#8cd06a', '#1f4a22'),
    '1': ('#c4f890', '#1f4a22'), '2': ('#6ad040', '#1f4a22'), '3': ('#3a9a2a', '#1f4a22'),
    'c': ('#8ae8f8', None), 'v': ('#2aa0c8', None),
    'y': ('#f2c040', '#3a2414'), 'o': ('#c7862a', '#3a2414'), 'Y': None,
    'e': ('#b4d878', None), 'f': ('#3a5a20', None),
    'p': ('#f0a0a0', None),
    'u': ('#d8e0e8', None), 's': ('#64707e', None), 'i': ('#dfe7ef', None),
    'b': ('#9ad0f4', '#163a5c'), 'd': ('#2a70b0', '#163a5c'),
}
del FIX['Y']


def G(text):
    """Grille 16×16 à partir d'un bloc de texte (rangées complétées par des points)."""
    rows = [r for r in text.strip('\n').split('\n')]
    rows = [r.ljust(16, '.')[:16] for r in rows]
    rows += ['.' * 16] * (16 - len(rows))
    assert len(rows) == 16, rows
    return rows


def geo(f):
    """Grille calculée : f(x, y) renvoie une lettre ou '.' (x, y = centre du pixel)."""
    return [''.join(f(x + .5, y + .5) for x in range(16)) for y in range(16)]


def layer(rows, outline=True):
    mask = {}
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch not in '. ':
                mask[(x, y)] = ch
    out = {}
    for (x, y), ch in mask.items():
        if ch in MATS:
            def ins(p):
                c = mask.get(p)
                return c is not None and (c == ch or c not in MATS)
            o, d, m, l = MATS[ch]
            if not ins((x, y - 1)) or not ins((x - 1, y)):
                out[(x, y)] = l
            elif not ins((x, y + 1)) or not ins((x + 1, y)):
                out[(x, y)] = d
            else:
                out[(x, y)] = m
        else:
            out[(x, y)] = FIX[ch][0]
    if outline:
        for y in range(16):
            for x in range(16):
                if (x, y) in mask:
                    continue
                col = None
                for p in ((x, y - 1), (x - 1, y), (x, y + 1), (x + 1, y)):
                    c = mask.get(p)
                    if c is None:
                        continue
                    oc = MATS[c][0] if c in MATS else FIX[c][1]
                    if oc and (col is None or c in MATS):
                        col = oc
                        if c in MATS:
                            break
                if col:
                    out[(x, y)] = col
    return out


def compose(*layers, put=None):
    px = {}
    for lay in layers:
        if isinstance(lay, list):
            lay = layer(lay)
        px.update(lay)
    if put:
        for (x, y), ch in put.items():
            px[(x, y)] = FIX[ch][0] if ch in FIX else ch
    im = Image.new('RGBA', (16, 16), (0, 0, 0, 0))
    for (x, y), c in px.items():
        if 0 <= x < 16 and 0 <= y < 16:
            h = c.lstrip('#')
            im.putpixel((x, y), tuple(int(h[i:i + 2], 16) for i in (0, 2, 4)) + (255,))
    return im


def mirror(rows):
    return [r[::-1] for r in rows]


def seg_dist(px, py, ax, ay, bx, by):
    vx, vy = bx - ax, by - ay
    t = max(0, min(1, ((px - ax) * vx + (py - ay) * vy) / (vx * vx + vy * vy)))
    return math.hypot(px - ax - t * vx, py - ay - t * vy), t


# ---------------------------------------------------------------- papiers

def livre():
    couv = G('''
................
................
................
................
................
................
................
................
................
................
................
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
''')
    gauche = G('''
................
................
................
..PPP...........
..PPPPPP........
..PnnnPP........
..PPPPPP........
..PnnnnP........
..PPPPPP........
..PnnnPP........
..PPPPPP........
..PPPPPP........
.....PPP........
''')
    droite = mirror(gauche)
    droite = [r.replace('n', 'P') for r in droite]
    droite[5] = droite[5][:9] + 'nnn' + droite[5][12:]
    droite[7] = droite[7][:9] + 'nnnn' + droite[7][13:]
    droite[9] = droite[9][:9] + 'nn' + droite[9][11:]
    return compose(couv, gauche, droite)


def parchemin():
    feuille = G('''
................
................
................
...QQQQQQQQQQ...
...QQQQQQQQQQ...
...QQQQQQQQQQ...
...QQnnnnnnQQ...
...QQQQQQQQQQ...
...QQnnnnnQQQ...
...QQQQQQQQQQ...
...QQnnnnnnQQ...
...QQQQQQQQQQ...
...QQQQQQQQQQ...
''')
    haut = G('''
................
................
..QQQQQQQQQQQQ..
..QQQQQQQQQQQQ..
''')
    bas = G('''
................
................
................
................
................
................
................
................
................
................
................
................
.QQQQQQQQQQQQ...
.QQQQQQQQQQQQ...
''')
    return compose(feuille, haut, bas,
                   put={(2, 3): 'q', (13, 2): 'q', (1, 13): 'q', (12, 12): 'q'})


def rapport():
    planche = G('''
................
................
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
..WWWWWWWWWWWW..
''')
    feuille = G('''
................
................
................
................
...PPPPPPPPPP...
...PPPPPPPPPP...
...PnnnnnnnPP...
...PPPPPPPPPP...
...PnnnnnnPPP...
...PPPPPPPPPP...
...PnnnnnnnPP...
...PPPPPPPPPP...
...PnnnnPPPPP...
...PPPPPPPPPP...
''')
    pince = G('''
................
......AAAA......
.....AAAAAA.....
.....AAAAAA.....
''')
    return compose(planche, layer(feuille, outline=False), pince, put={(7, 1): 'x', (8, 1): 'x'})


def lettre():
    env = G('''
................
................
................
................
................
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
..PPPPPPPPPPPP..
''')
    put = {}
    for i in range(6):
        put[(2 + i, 5 + i)] = 'k'
        put[(13 - i, 5 + i)] = 'k'
    for x, y in ((7, 9), (8, 9), (7, 10), (8, 10)):
        put[(x, y)] = 'r'
    put[(7, 9)] = 'j'
    put[(8, 10)] = 'h'
    return compose(env, put=put)


def boite(courrier):
    poteau = G('''
................
................
................
................
................
................
................
................
................
................
......WWW.......
......WWW.......
......WWW.......
......WWW.......
......WWW.......
''')
    caisse = G('''
................
................
................
....BBBBBBB.....
...BBBBBBBBB....
..BBBBBBBBBBB...
..BBBBBBBBBBB...
..BBBBBBBBBBB...
..BBBBBBBBBBB...
''')
    lay = [poteau, caisse]
    put = {}
    # porte à l'avant (gauche) : un trait plus sombre
    for y in range(4, 9):
        put[(3, y)] = 'd'
    put[(3, 4)] = 'b'
    if courrier:
        lay.append(G('''
................
................
................
................
................
.PPPPP..........
.PPPPP..........
'''))
        lay.append(G('''
................
...........RRRR.
...........RRRR.
...........R....
...........R....
...........R....
...........R....
'''))
    else:
        lay.append(G('''
................
................
................
................
................
................
..........RRRR..
..........RRRR..
'''))
    return compose(*lay, put=put)


# ---------------------------------------------------------------- outils

def cle_geo(head, tail, rh=3.3, rw=1.1, ring=True):
    """Clé plate : tête ouverte en `head`, manche jusqu'à `tail`."""
    hx, hy = head
    tx, ty = tail
    ax, ay = hx - tx, hy - ty
    n = math.hypot(ax, ay)
    ax, ay = ax / n, ay / n

    def f(x, y):
        dx, dy = x - hx, y - hy
        u = dx * ax + dy * ay
        v = -dx * ay + dy * ax
        if math.hypot(dx, dy) <= rh / 1.0 * 0.82:
            if u > -0.3 and abs(v) < 0.9:
                return '.'
            return 'A'
        d, t = seg_dist(x, y, tx, ty, hx, hy)
        if d <= rw:
            return 'A'
        return '.'
    return geo(f)


def cle():
    return compose(cle_geo((10.6, 5.4), (3.4, 12.6), rh=5.2, rw=1.45))


def marteau_cle():
    def manche(x, y):
        d, t = seg_dist(x, y, 3.2, 13.2, 10.5, 5.5)
        return 'W' if d <= 1.0 else '.'

    def tete(x, y):
        cx, cy = 11.0, 4.6
        u = ((x - cx) + (y - cy)) / math.sqrt(2)
        v = ((x - cx) - (y - cy)) / math.sqrt(2)
        return 'A' if abs(u) <= 3.4 and abs(v) <= 1.5 else '.'
    cl = cle_geo((4.6, 4.6), (12.8, 12.8), rh=4.2, rw=1.05)
    return compose(geo(manche), geo(tete), cl)


def ciseaux():
    moitie = G('''
................
.AA.............
.AAA............
..AAA...........
...AAA..........
....AAA.........
.....AAA........
......AAA.......
.......AAA......
.........AA.....
..........RRR...
.........RRRRR..
.........RR.RR..
.........RRRRR..
..........RRR...
''')
    return compose(moitie, mirror(moitie), put={(7, 7): 'y', (8, 7): 'o', (7, 8): 'o'})


def engrenage():
    cx = cy = 8.0

    def f(x, y):
        dx, dy = x - cx, y - cy
        r = math.hypot(dx, dy)
        a = math.atan2(dy, dx) + math.pi / 8
        dent = math.cos(8 * a) > 0.05
        if r <= 1.7:
            return '.'
        if r <= 5.0 or (dent and r <= 6.6):
            return 'A'
        return '.'
    return compose(geo(f))


def boite_outils():
    anse = G('''
................
................
.....AAAAAA.....
.....A....A.....
.....A....A.....
''')
    caisse = G('''
................
................
................
................
................
................
..RRRRRRRRRRRR..
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
.RRRRRRRRRRRRRR.
''')
    put = {(x, 8): 'h' for x in range(1, 15)}
    put.update({(7, 8): 'y', (8, 8): 'y', (7, 9): 'y', (8, 9): 'o'})
    return compose(anse, caisse, put=put)


# ---------------------------------------------------------------- énergie, électronique

def batterie():
    borne = G('''
................
......YYYY......
......YYYY......
''')
    corps = G('''
................
................
................
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
....AAAAAAAA....
''')
    put = {}
    for y in range(4, 14):
        for x in range(5, 11):
            put[(x, y)] = 'x'
    for y0 in (6, 9, 12):
        for x in range(5, 11):
            put[(x, y0)] = 'm' if x < 10 else 'l'
            if y0 + 1 <= 13:
                put[(x, y0 + 1)] = 'l' if x < 10 else 'g'
    for y in (8, 11):
        for x in range(5, 11):
            put[(x, y)] = 'x'
    put[(5, 6)] = '1'
    return compose(borne, corps, put=put)


def tableau():
    boitier = G('''
................
................
................
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
.SSSSSSSSSSSSSS.
''')
    put = {}
    for x in (3, 7):
        for y in range(5, 12):
            put[(x, y)] = 'x'
    # curseurs
    for x0, y0 in ((2, 6), (6, 9)):
        put[(x0, y0)] = 'w'
        put[(x0 + 1, y0)] = 'y'
        put[(x0 + 2, y0)] = 'y'
        put[(x0, y0 + 1)] = 'y'
        put[(x0 + 1, y0 + 1)] = 'o'
        put[(x0 + 2, y0 + 1)] = 'o'
    # boutons : rouge en haut, vert en bas
    for (x0, y0), (c1, c2, c3) in (((10, 5), ('j', 'r', 'h')), ((10, 9), ('1', 'l', 'g'))):
        put[(x0, y0)] = c1
        put[(x0 + 1, y0)] = c2
        put[(x0 + 2, y0)] = c2
        put[(x0, y0 + 1)] = c2
        put[(x0 + 1, y0 + 1)] = c2
        put[(x0 + 2, y0 + 1)] = c3
        put[(x0, y0 + 2)] = c2
        put[(x0 + 1, y0 + 2)] = c3
        put[(x0 + 2, y0 + 2)] = c3
        for x in range(x0 - 1, x0 + 4):
            put.setdefault((x, y0 + 3), 'x')
    return compose(boitier, put=put)


def capteur():
    antenne = G('''
................
...........r....
...........x....
...........x....
''')
    corps = G('''
................
................
................
................
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
..SSSSSSSSSSSS..
''')
    put = {}
    for y in range(5, 10):
        for x in range(3, 13):
            put[(x, y)] = 'x'
    for y in range(6, 9):
        for x in range(4, 12):
            put[(x, y)] = 'e'
    for x, y in ((4, 8), (5, 7), (6, 7), (7, 6), (8, 7), (9, 8), (10, 7), (11, 6)):
        put[(x, y)] = 'f'
    for x in (4, 7, 10):
        put[(x, 11)] = 'u'
        put[(x + 1, 11)] = 's'
    put[(12, 11)] = 'r'
    return compose(layer(antenne, outline=True), corps, put=put)


def douche():
    tuyau = G('''
................
................
.AAAAAAAA.......
........A.......
........A.......
''')
    pomme = G('''
................
................
................
................
................
.......AAA......
.....AAAAAAA....
....AAAAAAAAA...
''')
    gouttes = []
    for x, y in ((4, 10), (8, 11), (12, 10), (6, 14), (10, 14)):
        g = ['.' * 16 for _ in range(16)]
        g[y] = g[y][:x] + 'B' + g[y][x + 1:]
        if y + 1 < 16:
            g[y + 1] = g[y + 1][:x] + 'B' + g[y + 1][x + 1:]
        gouttes.append(g)
    put = {(x, 8): 'x' for x in range(5, 12)}
    put.update({(x, 8): 's' for x in (6, 8, 10)})
    # les gouttes sont posées sur le fond ; la dernière rangée reste hors cadre
    lays = [tuyau, pomme] + gouttes
    im = compose(*lays, put=put)
    return im


def microscope():
    socle = G('''
................
................
................
................
................
................
................
................
................
................
................
................
................
...SSSSSSSSSS...
...SSSSSSSSSS...
''')
    bras = G('''
................
................
................
................
.........SS.....
.........SSS....
..........SS....
..........SS....
..........SS....
..........SS....
.........SS.....
........SS......
........SS......
''')
    platine = G('''
................
................
................
................
................
................
................
................
................
...SSSSSSS......
''')

    def tube(x, y):
        d, t = seg_dist(x, y, 3.6, 1.8, 8.2, 7.4)
        r = 1.8 if t < 0.22 else (1.45 if t < 0.85 else 1.0)
        return 'A' if d <= r else '.'
    return compose(socle, bras, platine, geo(tube))


def eprouvette():
    verre = G('''
................
....TTTTTTTT....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
.....TTTTTT.....
......TTTT......
''')
    put = {}
    for y in range(7, 14):
        for x in range(5, 11):
            if verre[y][x] == 'T':
                put[(x, y)] = '2'
    for y in range(7, 14):
        put[(5, y)] = '1' if y < 13 else '2'
        if verre[y][10] == 'T':
            put[(10, y)] = '3'
    for x in range(5, 11):
        put[(x, 7)] = '1'
    put[(9, 13)] = '3'
    put[(7, 10)] = 'w'
    put[(8, 12)] = '1'
    put[(9, 9)] = '1'
    return compose(verre, put=put)


def robot():
    oreilles = G('''
................
................
................
................
................
................
................
.AAAAAAAAAAAAAA.
.AAAAAAAAAAAAAA.
.AAAAAAAAAAAAAA.
''')
    boule = G('''
................
.......RR.......
''')
    tete = G('''
................
................
................
................
...AAAAAAAAAA...
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
..AAAAAAAAAAAA..
...AAAAAAAAAA...
''')
    put = {}
    for y in range(6, 10):
        for x in range(3, 13):
            put[(x, y)] = 'x'
    for x0 in (5, 9):
        put[(x0, 7)] = 'w'
        put[(x0 + 1, 7)] = 'c'
        put[(x0, 8)] = 'c'
        put[(x0 + 1, 8)] = 'v'
    for x in range(6, 10):
        put[(x, 12)] = 'x'
    put[(5, 11)] = 'x'
    put[(10, 11)] = 'x'
    put[(3, 11)] = 'p'
    put[(12, 11)] = 'p'
    return compose(boule, oreilles, tete, put=put)


def icons():
    return {
        '📖': livre(),
        '📜': parchemin(),
        '📋': rapport(),
        '✉': lettre(),
        '📭': boite(False),
        '📬': boite(True),
        '🛠': marteau_cle(),
        '🔧': cle(),
        '✂': ciseaux(),
        '⚙': engrenage(),
        '🧰': boite_outils(),
        '🔋': batterie(),
        '🎛': tableau(),
        '📟': capteur(),
        '🚿': douche(),
        '🔬': microscope(),
        '🧪': eprouvette(),
        '🤖': robot(),
    }
